In [1]:
import pandas as pd
import re
import nltk
from nltk import word_tokenize,sent_tokenize
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
import string
from nltk.stem import PorterStemmer 
from sklearn.feature_extraction.text import TfidfVectorizer,CountVectorizer
from sklearn.decomposition import NMF, LatentDirichletAllocation
from sklearn.cluster import AgglomerativeClustering
import numpy as np
from sklearn.externals import joblib
from sklearn.cluster import KMeans
from sklearn.cluster import AgglomerativeClustering
from sklearn.metrics.pairwise import cosine_similarity

In [2]:
reviews = pd.read_csv('C:\\WPI\\InfoRet\\FinalProject\\data\\reviews_details.csv',encoding = "ISO-8859-1")
# reviews['listing_id'].value_counts()
# vc = reviews['listing_id'].value_counts()

In [3]:
def remove_nonalphanumeric(text):
    return re.sub("[^a-zA-Z0-9]"," ", str(text)).lower()

In [4]:
unique_listings = reviews.listing_id.unique()
len(unique_listings)

3986

In [5]:
reviews=reviews.groupby('listing_id').filter(lambda g: (g.listing_id.size >= 5))
reviews = reviews[reviews['listing_id'] != 15041925]
reviews = reviews[reviews['listing_id'] !=19102778]

unique_listings = reviews.listing_id.unique()
len(unique_listings)

2821

In [6]:
reviews['comments_1'] = reviews['comments'].apply(remove_nonalphanumeric)
reviews['tokenized_comments'] = reviews['comments_1'].apply(word_tokenize)
stopset = stopwords.words('english') + list(string.punctuation)
reviews['stop_comments'] = reviews['tokenized_comments'].apply(lambda x: [item for item in x if item not in stopset])
def func(row):
    return " ".join(row)
reviews['data'] = reviews['stop_comments'].apply(lambda x: func(x))



In [7]:
no_top_words = 5
no_top_documents = 10
result=[]

In [63]:
results_df2.to_csv("Result_kmeans.csv",columns=["topics","Review_comments","Review_Id","Listing_Id","Documents","Cluster"])

In [9]:
def top_tfidf_feats(row, features, top_n=10):
    ''' Get top n tfidf values in row and return them with their corresponding feature names.'''
    topn_ids = np.argsort(row)[::-1][:top_n]
    top_feats = [(features[i], row[i]) for i in topn_ids]
    df = pd.DataFrame(top_feats)
    df.columns = ['feature', 'tfidf']
    return df

In [10]:
def top_mean_feats(Xtr, features, grp_ids=None, min_tfidf=0.1, top_n=25):
    ''' Return the top n features that on average are most important amongst documents in rows
        indentified by indices in grp_ids. '''
    if grp_ids:
        D = Xtr[grp_ids].toarray()
    else:
        D = Xtr.toarray()

    D[D < min_tfidf] = 0
    tfidf_means = np.mean(D, axis=0)
    return top_tfidf_feats(tfidf_means, features, top_n)

In [23]:
#TEST CASE
results_df2 = pd.DataFrame()
for xx in range(0,1):
    listing_reviews=reviews[reviews['listing_id']==14586440]
    tf_vectorizer = TfidfVectorizer(max_df=0.80, min_df=2, max_features=500, stop_words='english',use_idf=True, ngram_range=(1,3))
    clust_tfidf= tf_vectorizer.fit_transform(listing_reviews['data'])
    terms = tf_vectorizer.get_feature_names()
    
    ###Calculate HAC
    num_clusters = 5
    dist = 1 - cosine_similarity(tfidf_matrix)
    linkage_matrix = AgglomerativeClustering(n_clusters=num_clusters) #define the linkage_matrix using ward clustering pre-computed distances
    HAC=linkage_matrix.fit_predict(dist)
    #print(tfidf_matrix)
    #print(HAC)
    #print(len(HAC))
    result=pd.DataFrame({'Review_comments':listing_reviews['comments'],'Review_Id':listing_reviews['id'],"Listing_Id":listing_reviews['listing_id'],"Documents": listing_reviews['data'], "Cluster":HAC })  
    
    

    #FIND MIN INDICES
    z=result['Cluster']
    ind=z.index.tolist()
    minind=min(ind)
    topics=[]
    clust_words=[]
    for j in range(0,5):
        subset=z[z==j]
        groups=subset.index.tolist()
        clust=[]
        for i in groups:
            clust.append(i-minind)
        x=top_mean_feats(clust_tfidf,terms,clust)

        words=[]
        for i in range(0,len(x)):
            words.append(x.iloc[i]['feature'])
        clust_words.append(words)
    topics=[]
    for i in range(0,len(HAC)):
        topics.append(clust_words[HAC[i]])
    print('TOPICS')
    result['topics']=topics
    results_df2 = results_df2.append(result)

   

TOPICS


In [32]:
results_df = pd.DataFrame()
for each_listing in unique_listings:
    print(each_listing)
    listing_reviews=reviews[reviews['listing_id']==each_listing]
    print(listing_reviews.shape)
    tf_vectorizer = TfidfVectorizer(max_df=0.80, min_df=2, max_features=500, stop_words='english',use_idf=True, ngram_range=(1,3))
    clust_tfidf= tf_vectorizer.fit_transform(listing_reviews['data'])
    terms = tf_vectorizer.get_feature_names()
    
    ###Calculate HAC
    num_clusters = 5
    dist = 1 - cosine_similarity(clust_tfidf)

    linkage_matrix = AgglomerativeClustering(n_clusters=num_clusters) #define the linkage_matrix using ward clustering pre-computed distances
    HAC=linkage_matrix.fit_predict(dist)
    #print(tfidf_matrix)
    print(HAC)
    print(len(HAC))
    
    result=pd.DataFrame({'Review_comments':listing_reviews['comments'],'Review_Id':listing_reviews['id'],"Listing_Id":listing_reviews['listing_id'],"Documents": listing_reviews['data'], "Cluster_HAC":HAC })  
    
    #FIND MIN INDICES
    z=result['Cluster_HAC']
    ind=z.index.tolist()
    minind=min(ind)
    topics=[]
    clust_words=[]
    for j in range(0,5):
        subset=z[z==j]
        groups=subset.index.tolist()
        clust=[]
        for i in groups:
            clust.append(i-minind)
        x=top_mean_feats(clust_tfidf,terms,clust)

        words=[]
        for i in range(0,len(x)):
            words.append(x.iloc[i]['feature'])
        clust_words.append(words)
    topics=[]
    for i in range(0,len(HAC)):
        topics.append(clust_words[HAC[i]])
    print('TOPICS')
    result['Topics_HAC']=topics
    results_df = results_df.append(result)
    
print(results_df)
results_df.to_csv("Result_HAC.csv",columns=["Topics_HAC","Review_comments","Review_Id","Listing_Id","Documents","Cluster_HAC"])

7441144
(5, 10)
[3 4 1 2 0]
5
TOPICS
12233830
(75, 10)
[2 2 2 0 0 2 2 2 4 2 2 2 4 2 2 2 2 2 2 2 1 2 0 2 1 1 2 2 2 1 2 4 2 0 0 1 2
 0 0 0 0 2 0 3 1 0 2 1 0 0 3 1 2 2 2 1 2 4 3 1 0 2 0 2 2 4 0 2 2 1 2 0 4 2
 1]
75
TOPICS
14586440
(99, 10)
[4 1 4 4 4 1 4 1 1 1 4 3 4 4 1 0 4 4 1 1 1 4 1 4 4 4 1 4 0 4 1 1 1 1 1 4 0
 1 1 4 2 4 4 0 4 4 0 1 1 1 1 1 4 3 4 1 4 1 4 0 4 1 1 0 0 4 4 1 1 4 4 1 0 1
 0 1 4 4 1 4 1 1 4 4 4 0 2 4 4 2 0 4 4 4 1 0 3 4 4]
99
TOPICS
15444930
(20, 10)
[3 2 0 4 3 0 2 4 4 1 1 1 2 1 0 0 2 3 0 3]
20
TOPICS
1596470
(68, 10)
[1 0 4 2 4 0 0 0 2 0 4 2 0 0 4 2 1 3 1 2 3 3 1 4 0 0 3 2 3 1 4 0 3 4 0 2 2
 0 0 4 2 1 2 2 4 0 3 2 1 0 4 3 2 0 3 3 2 2 1 2 0 2 2 0 2 2 0 4]
68
TOPICS
8211468
(16, 10)
[3 2 3 4 1 1 4 0 3 1 0 1 3 0 0 2]
16
TOPICS
8082512
(10, 10)
[4 4 0 3 1 1 2 3 0 2]
10
TOPICS
20726840
(6, 10)
[0 3 4 0 2 1]
6
TOPICS
17526985
(36, 10)
[0 0 0 2 4 0 0 2 1 0 2 2 3 2 0 1 4 2 3 0 4 0 3 1 1 0 1 2 2 2 2 2 1 2 2 4]
36
TOPICS
13707814
(5, 10)
[2 3 4 1 0]
5
TOPICS
16322051
(21, 10)
[0 3 2 

C:\Users\Claire Danaher\Anaconda3\lib\site-packages\scipy\cluster\hierarchy.py:471: ClusterWarning: scipy.cluster: The symmetric non-negative hollow observation matrix looks suspiciously like an uncondensed distance matrix
  return linkage(y, method='ward', metric='euclidean')



990668
(131, 10)
[4 1 1 0 1 1 0 0 0 1 1 0 0 1 1 0 1 1 1 4 1 0 0 3 0 0 2 4 3 4 0 0 0 0 0 0 0
 1 1 4 2 1 0 0 2 4 1 1 1 1 1 0 1 0 3 0 0 0 0 4 0 0 1 1 1 0 0 0 0 0 1 1 1 4
 0 0 0 0 0 3 0 1 0 0 1 3 0 0 0 4 1 1 2 2 0 1 0 0 0 4 1 0 1 0 1 0 1 3 2 1 0
 0 1 3 0 4 0 0 0 1 0 1 0 0 4 0 0 0 0 0 4]
131
TOPICS
19328794
(9, 10)
[4 2 1 0 1 0 2 3 4]
9
TOPICS
1494726
(13, 10)
[2 4 2 3 0 1 4 2 3 1 0 4 0]
13
TOPICS
15507108
(23, 10)
[1 1 2 4 1 2 2 1 2 0 0 2 3 3 2 0 4 3 3 0 0 2 0]
23
TOPICS
13054720
(119, 10)
[0 1 0 0 1 0 0 4 0 0 0 1 0 2 1 1 1 1 1 3 2 0 4 0 0 0 4 1 1 0 1 4 0 1 0 0 1
 1 1 3 3 0 1 0 1 1 1 1 4 1 0 0 0 1 3 0 0 1 4 0 1 0 0 0 4 1 4 1 1 1 0 1 0 4
 1 2 0 2 0 1 1 0 1 4 0 1 0 1 3 4 0 0 1 2 0 1 2 1 2 0 1 4 0 0 1 0 0 2 2 0 0
 1 2 0 2 1 1 3 0]
119
TOPICS
16600533
(12, 10)
[0 1 3 1 2 0 2 2 4 3 2 1]
12
TOPICS
19415743
(16, 10)
[1 1 3 0 1 4 3 1 2 2 2 0 4 0 1 1]
16
TOPICS
639111
(6, 10)
[4 3 1 0 2 0]
6
TOPICS
12210223
(18, 10)
[3 0 2 4 0 0 3 1 3 0 1 0 4 1 2 0 1 0]
18
TOPICS
15390344
(9, 10)
[1 3 1 3 0 0 4 2 

TOPICS
11964926
(84, 10)
[0 0 2 2 2 4 0 2 0 2 0 1 2 0 0 0 1 2 3 1 0 1 0 0 0 1 2 2 0 2 2 1 0 4 1 2 3
 0 1 2 1 3 4 0 1 1 2 0 1 1 2 1 0 4 1 1 0 4 4 4 1 2 4 2 1 0 2 0 0 0 3 0 4 1
 1 2 0 1 2 1 4 0 1 1]
84
TOPICS
5526487
(63, 10)
[0 0 4 2 4 4 0 1 0 1 0 0 1 0 0 1 0 3 1 0 0 0 1 1 4 0 1 0 2 3 1 3 4 1 0 4 0
 1 0 0 3 1 1 3 1 1 4 0 0 0 4 0 0 2 4 3 3 0 1 4 1 0 0]
63
TOPICS
6838488
(11, 10)
[0 4 4 1 3 3 1 0 2 2 0]
11
TOPICS
4645486
(28, 10)
[1 1 1 2 4 0 4 0 0 1 1 0 3 2 3 0 0 0 0 0 2 4 1 0 3 3 1 0]
28
TOPICS
4549374
(124, 10)
[0 4 0 0 1 3 3 3 4 4 1 0 0 1 4 1 0 0 0 0 0 0 0 0 1 0 4 0 0 0 1 2 0 0 1 0 1
 4 0 3 1 0 0 1 0 0 0 3 0 0 0 1 0 0 4 0 4 3 1 0 0 0 0 0 1 0 0 1 1 0 0 1 0 0
 1 3 0 0 0 3 3 0 1 1 1 3 0 1 0 0 3 1 0 1 1 2 0 0 1 0 1 1 3 1 0 3 1 0 1 2 0
 4 4 1 1 0 0 1 0 1 1 0 3 0]
124
TOPICS
19870249
(11, 10)
[2 0 0 3 1 2 4 4 3 1 1]
11
TOPICS
12752442
(63, 10)
[4 1 3 0 4 2 0 2 4 1 3 0 0 4 0 3 0 4 2 0 2 0 2 0 2 4 0 2 4 4 3 4 4 1 0 1 1
 2 0 4 2 2 4 4 4 1 0 3 2 4 4 2 1 2 2 4 2 0 2 4 0 0 3]
63
TOPICS
15232044
(

[3 0 3 3 1 3 0 3 2 4 0 3 3 3 0 1 3 3 0 0 0 0 0 3 3 0 3 0 0 0 0 4 3 0 0 0 1
 3 0 2 3 3 4 1 3 3 3 3 3 4 4 3 1 2 3 4 3 3 3 4 0 4 3 4 3 1 4 4 3 3 4 4 0 3
 3 3 0 2 3 4 0 4 4 3 3 2 1 1 0 3 3 4 4 2 0 3 4 0 2 0 1 0 3 1 0 3 4 3 3 4 0
 2 0 0 0 3 0 0 0 3 3 0 3 4 2 0 3 2 2 0 3 2 3 3 3 4 0 1 3 0 0 4 3 4 4 3 0 0
 0 1 3 3 3 3 0 4 4 3 4 4 1 4 2 0 0 3 2 0 3 4 0 4 0 4 1 0 3 3 3 4 4 3 3 2 2
 0 4 4 4 2 1 0 1 1 1 3 4 3 0 0 4 0 3 1 1 1 0 3 0 0 2 0 1 1 0 3 0 2 3 3 3 3
 0 1 0 4 3 2 3 2 3 3 0 3 0 1 2 3 4 4 0 2 4 0 4 0 1 1 0 2 0 0 0 2 1 0 3 4 4
 4 4 2 3 0 3 0 3 3 0 4 0 0 0 1 0 0 4 4 4 0 3 0 0 0 4 0 0 0 1 1 0 2 3 3 4 2
 4 4 2 0 4 1 0 0 4 1 2 0 0 4 0 0 0 0 4 4 4 1 3 3 0 0 4 4 4 0 3 0 3 0 1 3 0
 1 1 3 0 2 2 4 4 4 3 4 4 3 0 0 0 1 4 4 4 0 3 4 0 4 0 3 0 0 0 1 0 0 4 3 3 4
 4 3 0 3 0 4 0 1]
378
TOPICS
4603803
(13, 10)
[3 3 2 0 2 0 2 2 1 0 0 4 1]
13
TOPICS
18550644
(18, 10)
[2 1 1 4 1 3 3 1 1 1 1 0 0 0 2 0 2 0]
18
TOPICS
7472068
(70, 10)
[0 4 0 0 0 0 0 1 0 0 2 3 2 1 2 2 2 1 1 1 1 4 0 2 2 1 0 0 0 2 2 2 3 3 2 4 2
 0 4 0 3

[1 1 3 1 0 2 0 3 0 1 0 3 1 0 0 0 1 3 0 1 1 0 1 0 0 0 0 0 3 0 3 1 0 1 0 0 2
 4 2 0 1 2 0 0 3 0 0 1 0 3 0 0 1 1 0 1 0 0 1 1 4 1 0 3 0 0 4 0 1 1 1 0 0 3
 0 0 0 1 0 0 1 0 1 0 3 1 2 0 0 1 0 0 0 4 1 0 1 1 0 0 1 0 1 0 4 0 0 0 0 0 0
 2 2 3 2 3 2 0 1 0 0 1 1 0 0 4 3 3 0 3 3 0 0 0 2 0 0 2 2 1 1 0 4 0 0 0 4 0
 3 1 1 0 0 0 1 4 0 1 4 0 0 0 1 3 1 1 3 3 0 2 0 0 1 4 2 0 3 0 4]
179
TOPICS
12291029
(26, 10)
[4 3 4 3 1 1 4 0 0 3 0 2 1 1 1 2 0 0 1 2 2 0 1 2 1 2]
26
TOPICS
13614982
(18, 10)
[3 4 0 0 4 2 3 4 0 0 1 1 2 0 1 2 3 2]
18
TOPICS
2000797
(96, 10)
[2 0 0 2 1 2 2 2 0 2 2 1 2 2 0 0 2 3 2 3 2 2 2 3 1 3 3 2 4 3 2 2 2 1 2 1 0
 1 2 4 2 1 2 0 0 0 1 3 1 2 0 2 0 0 0 0 2 0 3 2 2 2 0 2 4 1 2 2 2 0 4 2 2 1
 1 2 4 2 2 4 2 0 4 0 0 2 1 1 2 2 0 2 0 2 0 2]
96
TOPICS
10249798
(17, 10)
[2 1 1 3 3 0 0 3 0 4 1 0 4 2 1 0 0]
17
TOPICS
3601030
(125, 10)
[0 0 0 0 0 4 0 0 0 0 0 0 2 2 0 0 0 0 0 0 4 0 0 0 2 0 0 0 1 0 0 1 0 0 0 0 3
 4 0 0 3 0 0 0 0 4 0 0 0 0 0 0 0 0 0 4 0 0 0 0 0 0 0 0 3 0 0 0 0 1 0 0 0 0
 0 0 0 0 0 0 0 0 4 0 0

7
TOPICS
16845972
(94, 10)
[0 4 2 2 4 3 0 2 2 3 1 4 4 4 0 4 3 2 3 1 4 1 4 4 4 1 0 1 4 3 1 3 2 3 3 2 0
 1 4 2 2 0 4 1 3 1 4 4 2 3 0 0 3 4 2 4 3 1 3 3 4 2 4 4 0 4 0 0 4 2 2 4 0 4
 2 1 4 1 1 2 0 3 4 2 3 4 2 0 3 1 1 1 0 4]
94
TOPICS
15543038
(5, 10)
[3 4 2 1 0]
5
TOPICS
2754149
(69, 10)
[4 0 0 1 0 0 1 1 0 2 0 2 1 0 0 0 4 4 0 0 0 0 0 1 1 0 0 0 1 0 2 3 4 0 3 4 0
 0 0 1 4 0 0 0 1 1 4 4 0 0 0 2 4 0 1 1 3 3 4 0 3 1 4 0 1 4 4 4 1]
69
TOPICS
19154786
(15, 10)
[0 0 2 4 3 4 1 3 2 2 3 1 0 1 1]
15
TOPICS
12040113
(8, 10)
[2 0 2 1 0 4 1 3]
8
TOPICS
8703026
(94, 10)
[0 2 0 3 4 4 0 0 0 0 2 4 1 0 2 2 0 2 0 1 3 0 2 2 0 0 0 0 0 2 1 0 0 2 0 2 2
 0 2 0 0 1 0 2 2 0 2 1 1 0 2 1 4 0 1 2 2 1 1 0 2 4 1 4 0 2 4 1 0 0 1 0 0 0
 2 2 0 1 0 2 0 0 2 2 1 3 2 1 0 1 0 0 3 4]
94
TOPICS
18240259
(12, 10)
[4 2 1 0 0 1 3 0 4 4 2 3]
12
TOPICS
19506279
(6, 10)
[3 2 4 0 0 1]
6
TOPICS
6066455
(101, 10)
[4 1 1 0 3 0 4 1 1 4 0 1 1 1 1 2 1 2 1 0 1 4 1 4 1 1 1 0 1 3 4 1 1 1 0 4 1
 4 4 4 4 1 1 4 1 3 1 3 3 1 0 4 1 1 4 4 1 4 0 0 1 2 4 1 

TOPICS
17280729
(6, 10)
[0 3 2 4 1 0]
6
TOPICS
15429888
(10, 10)
[0 0 2 0 1 3 0 2 4 1]
10
TOPICS
14074739
(25, 10)
[0 2 0 2 2 0 4 0 1 3 0 0 2 3 1 4 3 4 2 0 2 1 0 1 0]
25
TOPICS
15122796
(15, 10)
[3 0 1 2 1 1 1 1 4 4 1 3 2 0 0]
15
TOPICS
8688811
(26, 10)
[0 1 2 1 0 4 1 3 1 0 1 1 0 1 1 1 0 1 1 4 2 0 1 2 0 3]
26
TOPICS
15194685
(5, 10)
[4 3 2 1 0]
5
TOPICS
5768819
(16, 10)
[2 0 2 0 0 2 0 4 4 1 4 3 3 0 2 1]
16
TOPICS
20649021
(9, 10)
[1 0 0 2 0 4 1 2 3]
9
TOPICS
2931165
(106, 10)
[4 1 4 1 0 1 1 0 1 0 0 4 4 1 0 0 4 3 0 1 1 0 0 4 1 0 0 0 4 1 4 1 1 1 0 0 1
 4 4 0 0 0 1 0 0 1 2 4 1 4 1 1 4 1 1 2 4 4 4 1 1 0 1 4 2 3 4 0 4 4 0 0 4 1
 4 2 0 3 1 1 4 4 2 4 4 4 4 4 2 4 2 1 4 0 0 1 2 0 4 4 0 2 1 2 1 4]
106
TOPICS
9208166
(106, 10)
[1 1 2 1 1 3 2 0 2 0 1 2 0 0 0 0 0 0 1 0 0 1 1 2 0 4 2 0 1 1 0 2 2 0 2 0 1
 0 2 1 0 0 0 0 0 2 3 0 2 0 0 2 4 0 2 0 0 3 0 2 0 0 0 2 4 0 3 0 2 3 0 0 3 0
 1 0 1 0 0 3 0 0 0 2 3 4 2 4 1 3 1 0 4 4 2 0 3 4 2 1 1 2 2 2 2 0]
106
TOPICS
11082235
(57, 10)
[0 1 0 1 1 0 1 0 2 3 2 0 0 2 

[3 2 1 2 3 2 0 0 4 1 0 4]
12
TOPICS
1109224
(51, 10)
[1 1 3 1 1 0 1 2 0 1 1 4 1 3 1 1 3 2 1 0 1 2 0 0 0 1 3 1 1 3 1 1 3 1 0 0 1
 4 1 3 3 2 3 3 3 1 1 0 1 1 1]
51
TOPICS
4263736
(155, 10)
[0 0 0 0 4 1 1 3 1 3 1 0 1 3 0 3 4 0 4 1 4 4 3 0 4 4 1 1 1 1 4 3 1 1 1 1 4
 1 1 4 0 0 1 0 4 3 1 3 1 2 4 3 3 0 2 4 1 4 1 0 0 1 3 4 1 1 1 4 0 4 1 4 1 4
 1 1 3 1 3 4 1 4 0 3 1 4 0 0 4 0 3 1 1 4 2 4 1 3 3 0 0 1 2 4 1 1 1 1 0 0 1
 0 1 1 1 1 1 2 0 1 3 2 3 1 1 2 1 1 1 0 4 0 4 0 4 1 0 1 1 0 1 2 4 1 4 1 1 3
 1 2 0 0 1 3 3]
155
TOPICS
19965562
(5, 10)
[2 3 4 1 0]
5
TOPICS
5101552
(37, 10)
[2 0 0 0 2 0 0 0 2 1 1 0 0 3 4 3 1 3 3 4 1 4 0 4 1 0 0 0 0 1 0 1 3 4 3 1 0]
37
TOPICS
12618291
(7, 10)
[2 0 4 2 0 3 1]
7
TOPICS
15134020
(64, 10)
[0 2 2 2 1 3 4 3 2 2 2 2 1 0 0 2 2 2 3 2 2 2 2 3 2 3 2 2 2 0 0 4 0 4 0 2 2
 2 4 1 0 0 0 1 0 2 3 0 4 2 4 1 1 0 3 2 1 2 1 3 1 3 1 2]
64
TOPICS
10356880
(88, 10)
[1 1 1 0 1 1 0 1 4 1 4 4 2 4 0 2 1 2 2 4 2 1 0 4 1 3 0 4 1 4 2 4 2 3 0 4 4
 0 1 4 4 0 1 0 1 1 2 1 2 4 4 0 1 2 2 4 0 2 4 1 1 0 0

10
TOPICS
10228457
(24, 10)
[3 1 3 3 0 0 0 0 1 1 4 3 2 0 0 1 0 0 2 0 0 4 1 1]
24
TOPICS
15054000
(5, 10)
[4 3 1 2 0]
5
TOPICS
18686660
(38, 10)
[3 4 3 1 0 0 2 4 0 3 3 2 4 4 3 2 1 1 3 3 3 2 0 4 1 4 0 1 0 3 4 4 0 3 4 0 0
 0]
38
TOPICS
15374913
(109, 10)
[2 2 2 0 0 1 1 0 0 0 0 0 0 0 2 1 1 2 0 2 0 1 1 1 0 1 0 0 0 2 2 2 2 0 0 0 0
 1 1 2 0 0 2 0 0 0 0 0 1 0 0 2 4 0 2 1 2 0 0 0 1 0 0 2 2 0 1 0 0 0 1 0 0 0
 0 0 0 1 0 1 0 1 4 2 4 1 1 0 1 0 2 0 0 2 0 1 0 0 0 0 2 2 1 1 3 3 3 3 0]
109
TOPICS
7635616
(21, 10)
[1 3 2 1 3 4 0 2 2 2 0 1 0 0 1 2 4 0 0 2 1]
21
TOPICS
14966548
(68, 10)
[2 4 1 2 4 0 1 0 0 3 1 0 1 1 1 0 1 1 4 1 2 1 1 0 1 1 4 4 1 1 3 1 0 0 1 0 1
 4 0 1 1 1 1 1 1 1 0 0 1 2 0 1 1 0 0 3 3 4 1 1 3 4 1 1 1 4 0 1]
68
TOPICS
14040282
(31, 10)
[4 1 0 4 0 0 0 1 0 4 1 0 1 1 4 0 0 4 3 3 4 0 2 0 2 4 1 3 4 3 4]
31
TOPICS
4331214
(58, 10)
[1 0 4 1 4 2 0 0 4 0 1 2 0 1 1 1 0 0 1 1 1 0 0 0 1 0 0 3 0 1 0 1 0 0 0 2 1
 1 0 0 2 2 0 1 1 1 1 2 0 1 1 2 3 0 1 2 0 1]
58
TOPICS
9463444
(33, 10)
[4 1 4 4 0 1 4 3 0 4 0

[1 0 2 1 0 3 2 1 3 1 1 0 0 1 1 1 3 1 1 2 1 1 1 0 1 1 3 1 1 4 1 1 3 1 0 3 1
 1 4 2 1 0 1 3 1 1 0 1 3 1 1 0 3 4 0 2 3 0 0 1 0 0 0 2 1 0 1 0 2 0 0 1 1 1
 0 4 0 1 0 0 0 2 1 0 0 1 4 1 0 1 0 0 1 3 1 1 1 1 1 1 0 1 1 0 0 1 3 0 1 0 0
 1 0 1 3 1 0 1 3 0 0 0 2 1 4 1 3 0 0 1 0 1 1 1 1 2 1 4 1 1 2 2 1 1 1 0 1 0
 0 1 3 0 2 0 1 3 0 1 0 0 1 3 3 0 0 1 3 0 0 0 4 4 1 3 1 0 0 1 0 0 2 2 0 3 1
 0 3 2 1 0 0 0 1 1 3 0 1 1 2 0 0 1 0 0 1 1 1 1 0 0 2 0 0 0 0 0 1 2 2 3 1 1
 3 0 0 1 0 4 3 0 0 2 0 0 2 0 2 1 0 1 1 2 3 1 1 0 1 1 1 1 0 0 1 1 2 0 2 0 2
 2 0 0 0 3 0 1 0 0 1 1 1 0 0 3 0 0 0 1 3 1 1 1 1 1 4 0 0 3 0 0 1 0 0 2 2 0
 1 2 0 0 0 3 1 0 0 1 1 1 0 0 2 1 0 2 1 0 0 0 1 0 0 1 0 4 0 0 0 1 0 1 0 1 0
 0 0 0 2 0 0 4 2]
341
TOPICS
18376849
(11, 10)
[3 3 1 4 4 0 0 2 0 2 1]
11
TOPICS
11223924
(95, 10)
[4 0 4 0 0 2 0 4 0 0 2 1 1 4 0 2 2 0 0 1 2 1 0 0 1 2 4 4 3 3 4 1 2 2 2 2 0
 2 0 2 3 2 1 1 0 2 2 0 2 1 1 0 2 2 0 0 0 2 3 3 0 1 2 0 1 2 1 0 2 2 0 2 2 0
 2 2 4 2 1 2 0 2 2 3 1 1 0 2 2 2 2 2 0 2 2]
95
TOPICS
13686161
(15, 10)
[4 3

TOPICS
6780313
(52, 10)
[4 0 0 0 0 0 3 0 0 1 4 1 0 3 0 0 1 0 0 0 0 0 0 2 1 1 3 1 0 3 0 0 0 2 0 1 2
 0 4 2 1 1 1 0 1 4 2 0 1 4 2 1]
52
TOPICS
19602358
(21, 10)
[0 3 0 1 4 1 2 1 1 0 1 3 0 2 0 4 0 4 0 2 0]
21
TOPICS
15375825
(11, 10)
[3 0 1 2 4 1 0 3 0 2 0]
11
TOPICS
18412267
(14, 10)
[0 1 4 3 2 3 1 0 2 0 0 4 2 4]
14
TOPICS
13140867
(65, 10)
[3 2 1 0 4 0 1 3 0 3 3 0 3 2 0 4 0 0 2 3 0 2 3 3 0 2 2 4 3 0 4 1 4 2 3 3 0
 0 2 0 0 2 1 4 2 2 4 3 0 0 2 0 0 1 1 2 0 4 2 2 4 2 3 4 0]
65
TOPICS
15580808
(9, 10)
[0 0 4 0 2 2 3 1 2]
9
TOPICS
11343485
(32, 10)
[1 1 0 0 0 0 1 1 4 4 1 2 2 0 1 0 1 1 1 0 1 2 2 1 1 2 2 3 1 2 2 3]
32
TOPICS
568234
(176, 10)
[2 0 0 0 0 0 0 0 0 1 0 1 0 0 1 0 1 0 0 4 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0
 0 0 0 0 1 0 0 0 0 0 0 2 0 0 0 0 0 0 0 1 1 4 1 4 3 3 3 0 0 0 0 0 0 3 0 2 0
 0 1 0 3 0 0 0 3 0 0 2 2 1 3 0 0 0 1 0 1 0 0 4 0 0 0 2 0 1 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 1 0 0 4 1 0 1 1 0 2 1 0 0 1 0 0 1 0 0 0 2 0 0 4 0 2 1 0 0 0 2
 0 2 0 1 1 0 0 0 2 0 0 2 0 1 2 0 0 0 0 1 1 2 0 0 0 0 0 0]
1

(106, 10)
[3 0 0 0 0 0 2 0 0 0 0 1 4 0 0 4 0 0 0 0 0 4 0 0 0 0 0 1 0 4 0 1 0 0 4 0 0
 0 4 0 2 0 3 2 0 0 0 0 0 4 0 0 0 0 0 0 4 4 0 1 4 0 0 0 2 1 4 0 0 0 4 2 0 0
 0 0 0 4 1 4 2 2 3 0 3 0 2 0 0 0 2 0 0 1 2 0 1 0 0 0 0 0 0 1 2 0]
106
TOPICS
16272452
(54, 10)
[4 0 3 3 4 2 2 1 0 1 3 4 0 1 4 0 0 4 1 3 0 2 0 0 4 2 4 2 0 0 0 1 1 2 1 0 0
 0 2 0 0 2 0 3 0 4 4 1 0 0 1 0 0 0]
54
TOPICS
2660908
(15, 10)
[1 0 2 1 4 4 2 3 3 3 0 1 3 0 1]
15
TOPICS
14274311
(100, 10)
[0 0 1 3 0 0 1 0 0 2 2 1 0 1 0 4 1 0 2 0 0 0 0 0 1 0 0 0 0 1 0 1 1 1 0 1 0
 1 1 3 1 0 0 0 0 0 0 4 0 1 2 1 0 0 0 2 4 0 0 4 0 0 0 0 0 1 0 4 0 4 1 1 0 2
 0 0 0 1 0 0 0 0 0 1 0 0 0 4 0 0 0 0 1 3 0 0 4 0 1 1]
100
TOPICS
9885963
(16, 10)
[4 0 0 4 1 3 0 0 1 1 2 0 1 4 0 2]
16
TOPICS
13101775
(10, 10)
[3 0 4 1 0 2 0 1 1 1]
10
TOPICS
6914622
(13, 10)
[2 0 0 0 1 1 4 1 0 4 3 2 3]
13
TOPICS
1038465
(193, 10)
[0 2 2 2 2 2 1 2 0 0 2 2 4 1 2 2 2 2 0 2 1 2 1 2 2 2 2 0 0 2 0 0 2 2 0 2 1
 2 1 2 0 2 1 1 1 0 3 2 0 2 2 2 2 0 0 0 2 1 2 4 0 2 0 0 2 0 0 2 0 0 2 2 2

11563716
(8, 10)
[3 2 4 1 0 0 1 2]
8
TOPICS
11653496
(25, 10)
[2 0 1 2 2 3 0 2 0 1 4 2 1 1 3 2 1 1 1 2 0 3 3 4 0]
25
TOPICS
5659866
(10, 10)
[4 4 0 0 1 0 2 3 1 0]
10
TOPICS
1332786
(220, 10)
[1 1 4 0 1 2 0 1 2 1 0 2 4 0 0 0 2 1 1 0 0 1 4 4 1 1 0 1 0 0 0 1 1 0 2 4 0
 0 0 0 0 0 1 1 1 0 0 2 0 0 0 0 0 2 1 0 1 0 0 0 0 1 2 0 0 1 0 1 1 0 0 2 0 3
 0 3 3 0 0 1 0 1 1 4 1 0 0 1 4 0 2 3 0 1 0 4 1 1 0 2 4 1 2 4 1 0 0 3 2 4 1
 0 1 3 1 2 0 0 0 4 0 4 0 1 1 2 0 0 1 3 0 0 0 1 0 0 0 0 2 1 4 0 3 2 2 1 1 1
 0 0 0 0 0 3 0 2 1 3 2 3 2 1 1 3 4 2 1 0 1 0 3 1 3 0 3 0 0 3 2 0 0 1 0 1 0
 0 0 3 0 0 0 0 4 0 0 1 0 0 1 2 4 0 2 0 1 2 0 0 2 0 1 3 0 2 1 0 3 0 0 2]
220
TOPICS
67774
(28, 10)
[1 0 3 1 4 1 2 1 0 3 4 3 2 0 0 0 2 0 3 4 0 1 2 0 2 0 3 0]
28
TOPICS
7036112
(7, 10)
[3 0 2 4 2 1 0]
7
TOPICS
9477550
(14, 10)
[0 3 0 1 2 0 3 1 1 1 1 3 2 4]
14
TOPICS
11662212
(154, 10)
[0 0 0 0 0 0 1 1 0 0 1 0 1 1 0 0 0 0 0 1 4 4 1 0 1 2 0 1 1 4 1 1 0 0 0 0 0
 2 3 4 0 0 1 0 2 0 3 0 0 1 1 0 0 1 0 4 0 4 4 1 1 1 4 0 4 0 0 0 1 0 0 0 0 1
 

TOPICS
2187766
(24, 10)
[4 2 2 0 0 3 1 1 0 0 1 0 1 3 1 0 0 0 0 2 4 2 1 0]
24
TOPICS
20817599
(7, 10)
[0 2 3 0 1 4 1]
7
TOPICS
19787044
(5, 10)
[4 3 1 2 0]
5
TOPICS
10231714
(39, 10)
[0 1 3 2 0 1 2 0 4 0 2 2 4 0 4 1 1 1 2 2 4 4 1 1 0 4 4 0 1 4 2 4 2 2 4 4 4
 0 3]
39
TOPICS
381187
(12, 10)
[2 0 1 3 2 3 1 4 2 0 2 0]
12
TOPICS
20901417
(5, 10)
[3 4 2 1 0]
5
TOPICS
4820071
(264, 10)
[0 4 0 0 4 4 0 0 0 0 1 4 0 0 4 1 1 0 4 0 0 4 0 1 4 3 0 1 1 0 4 0 4 0 0 1 4
 4 4 0 4 4 4 0 4 0 4 0 0 0 0 0 0 0 1 4 0 1 0 1 0 1 0 0 4 4 0 0 0 0 0 0 0 1
 0 4 0 3 4 4 4 0 4 1 0 4 1 0 0 0 3 0 3 1 4 3 0 0 0 0 0 0 1 0 0 0 0 4 4 4 0
 0 1 1 1 0 0 4 0 0 0 4 1 1 4 0 0 1 0 4 0 0 0 2 2 2 2 0 0 0 4 4 0 1 1 4 4 0
 0 1 4 1 4 0 0 4 1 1 0 1 1 0 0 0 0 0 0 2 0 0 0 1 4 0 0 4 3 4 4 4 1 0 0 4 4
 1 0 1 0 4 0 0 1 4 0 0 0 0 4 0 0 1 0 1 0 0 1 0 0 0 0 4 0 0 0 4 0 0 0 0 0 1
 0 0 4 1 4 4 1 0 0 4 0 4 4 0 4 0 0 0 0 0 4 0 0 4 0 0 0 4 0 0 0 1 1 0 4 4 0
 0 0 1 1 1]
264
TOPICS
3641545
(6, 10)
[4 0 2 0 3 1]
6
TOPICS
18228183
(7, 10)
[3 0 0 2 4 1 2]

2331886
(81, 10)
[1 1 1 1 4 1 1 2 1 0 1 4 4 0 2 2 1 0 0 1 1 2 1 1 2 1 3 1 1 1 2 0 1 2 1 1 2
 3 0 1 1 1 1 1 2 3 3 1 2 1 0 0 4 1 2 0 1 1 0 1 2 1 2 2 2 2 0 0 2 1 0 0 3 2
 0 1 3 1 1 0 2]
81
TOPICS
19005408
(21, 10)
[2 1 0 3 2 4 1 1 1 1 0 0 0 3 3 0 0 2 0 4 2]
21
TOPICS
1421610
(6, 10)
[4 0 2 0 3 1]
6
TOPICS
9459945
(6, 10)
[0 0 4 3 2 1]
6
TOPICS
19117781
(34, 10)
[2 0 0 0 0 0 2 1 1 1 1 1 3 3 1 2 1 0 0 3 3 0 3 1 0 0 0 0 4 1 0 0 0 4]
34
TOPICS
12781774
(36, 10)
[2 4 0 1 0 4 2 0 1 0 1 4 2 0 0 1 0 0 0 2 2 3 0 2 0 1 0 0 0 4 1 1 0 2 3 2]
36
TOPICS
13414367
(20, 10)
[1 1 1 0 0 4 4 0 2 0 0 1 3 0 1 3 2 2 1 3]
20
TOPICS
2776391
(85, 10)
[0 2 2 1 2 0 2 2 0 0 2 1 2 0 2 2 2 0 2 2 2 2 2 2 3 1 0 0 0 0 2 0 2 2 2 2 2
 0 2 2 2 1 2 0 1 2 2 4 2 0 1 2 2 4 2 2 4 0 2 0 3 2 0 2 2 2 0 2 2 2 1 4 2 0
 2 0 0 0 0 0 0 0 0 2 0]
85
TOPICS
8224214
(91, 10)
[1 0 1 1 0 0 0 0 1 0 0 2 4 0 0 0 1 1 0 0 0 2 0 2 1 0 0 0 0 0 3 0 3 0 0 1 0
 0 1 0 0 0 0 0 0 0 0 2 0 0 4 0 0 0 1 4 1 1 0 0 0 0 1 0 0 0 1 4 3 0 0 0 1 1
 0 0 0 0 1 1 4 0 1 

3591388
(41, 10)
[1 1 0 0 0 4 2 1 0 1 1 1 4 2 2 0 4 3 4 1 3 1 0 1 1 4 0 0 4 0 2 4 0 1 1 4 2
 0 4 4 0]
41
TOPICS
11921486
(22, 10)
[4 1 0 1 1 4 4 1 0 3 1 0 0 2 0 2 3 4 0 1 0 0]
22
TOPICS
17923033
(5, 10)
[3 4 2 1 0]
5
TOPICS
8112652
(6, 10)
[0 3 2 4 0 1]
6
TOPICS
4445906
(5, 10)
[3 4 1 2 0]
5
TOPICS
16150461
(6, 10)
[4 3 2 1 0 0]
6
TOPICS
6741968
(162, 10)
[1 0 0 0 0 2 0 0 2 0 1 0 0 0 1 1 1 0 0 0 1 0 2 1 0 2 0 0 0 3 1 3 0 1 0 0 1
 1 0 1 1 1 1 0 1 0 1 0 1 1 0 0 2 0 1 1 1 2 0 0 0 2 0 0 3 0 0 0 1 1 0 0 0 1
 1 0 2 1 0 1 1 3 0 0 0 1 1 0 1 3 0 0 1 3 0 3 1 3 3 1 0 1 0 0 0 0 1 4 0 2 1
 1 0 0 1 0 0 0 4 0 3 0 0 3 1 1 0 1 3 3 0 1 1 1 0 4 1 0 1 0 3 0 1 0 2 0 2 1
 0 0 0 0 3 0 0 0 0 0 0 0 2 0]
162
TOPICS
11624428
(7, 10)
[3 2 4 0 0 2 1]
7
TOPICS
1102623
(66, 10)
[1 0 0 0 2 1 2 1 0 0 1 2 0 2 1 1 1 0 1 1 0 1 1 1 2 2 2 0 0 1 1 1 1 1 0 1 2
 1 1 1 1 1 2 1 2 0 1 1 0 0 0 1 1 4 2 1 3 0 3 0 1 4 0 1 1 1]
66
TOPICS
16690607
(67, 10)
[0 0 1 1 0 4 0 1 4 2 3 1 2 4 3 0 3 1 3 1 0 0 0 4 1 4 3 0 3 2 1 2 1 3 3 0 0
 0 0

TOPICS
13028935
(8, 10)
[2 0 0 3 4 2 1 0]
8
TOPICS
496022
(16, 10)
[4 2 1 0 0 3 2 3 4 0 4 0 1 2 1 4]
16
TOPICS
18898296
(21, 10)
[2 3 2 0 0 0 4 1 1 0 0 2 3 0 0 0 0 2 1 0 4]
21
TOPICS
13751426
(41, 10)
[0 1 1 0 1 0 0 2 0 2 0 2 0 0 1 0 2 0 2 4 2 3 3 1 2 3 1 1 0 0 1 0 2 4 2 1 1
 0 4 2 0]
41
TOPICS
176006
(116, 10)
[0 0 0 1 2 0 0 0 0 1 0 0 3 1 1 0 1 0 1 0 3 1 2 1 0 0 0 1 2 0 3 0 0 2 0 1 0
 1 0 1 0 4 0 0 1 2 0 0 0 0 0 1 0 1 0 1 1 0 1 1 1 2 1 1 2 3 1 1 1 3 4 1 2 1
 2 2 1 1 2 3 1 4 2 2 1 1 1 1 1 0 1 1 1 1 1 1 0 1 1 1 2 1 1 1 1 1 1 1 0 2 0
 0 1 1 0 1]
116
TOPICS
19661260
(13, 10)
[0 0 3 0 4 4 1 1 1 2 3 0 2]
13
TOPICS
2649521
(9, 10)
[1 2 3 2 2 1 0 0 4]
9
TOPICS
8417742
(33, 10)
[2 2 1 4 1 4 4 0 1 0 1 1 1 3 3 3 1 2 0 1 3 1 1 3 1 4 0 3 4 4 0 0 0]
33
TOPICS
4447990
(64, 10)
[0 3 0 0 0 0 0 0 0 0 0 0 0 1 4 0 0 0 2 2 0 4 0 0 0 1 0 0 0 2 0 0 0 0 0 0 0
 0 0 2 0 0 0 0 0 0 3 2 2 2 2 2 0 0 2 0 0 0 0 0 0 0 0 1]
64
TOPICS
14473053
(10, 10)
[1 2 0 3 4 2 1 1 0 1]
10
TOPICS
16172035
(41, 10)
[2 0 2 2 1 1 0 1 

16274148
(53, 10)
[0 0 4 2 0 0 0 3 4 1 0 1 0 1 2 4 3 0 4 0 0 2 2 1 0 3 0 0 0 4 1 0 0 1 4 3 0
 2 4 1 1 0 2 0 0 0 0 4 0 0 4 2 0]
53
TOPICS
15616726
(46, 10)
[0 2 1 0 0 4 0 1 0 1 1 2 4 0 0 0 0 0 2 0 0 4 2 3 0 1 0 2 0 2 1 0 4 0 0 3 1
 1 0 1 4 1 2 0 0 0]
46
TOPICS
3969526
(191, 10)
[3 3 0 3 3 3 3 3 1 3 4 0 3 1 3 3 3 3 0 1 4 0 3 3 4 1 3 3 3 0 3 3 3 0 3 0 0
 3 3 3 3 0 3 3 0 3 0 3 3 3 1 3 3 0 1 3 0 3 3 3 3 2 3 3 1 3 0 1 4 3 3 3 2 4
 3 3 0 3 3 4 1 3 3 3 1 0 3 4 3 3 3 3 3 3 4 2 1 1 3 0 3 0 0 3 3 0 1 3 1 3 3
 3 0 3 0 0 1 0 3 1 0 4 3 0 3 1 1 3 3 3 3 1 3 0 3 4 3 3 3 2 1 1 4 1 0 3 1 3
 3 3 0 1 1 3 0 3 3 0 0 3 0 4 3 3 0 1 3 3 4 0 1 3 0 3 3 3 4 0 0 3 0 1 0 1 3
 3 3 3 3 3 1]
191
TOPICS
20091759
(8, 10)
[0 2 1 2 0 3 4 1]
8
TOPICS
17609382
(22, 10)
[0 4 2 1 1 0 2 4 0 1 4 3 3 0 2 2 0 3 1 0 1 1]
22
TOPICS
47521
(290, 10)
[3 0 0 3 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 3 0 2 0 0 0 0 0 1 0 0
 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 4 0 0 0 1 0 0 0 4 0 0 0 3 0 0 0 0 1
 0 0 0 1 0 0 0 0 3 0 0 0 0 1 4 0 0 0 0

6936712
(11, 10)
[2 4 1 1 1 3 0 2 3 0 0]
11
TOPICS
10569282
(60, 10)
[3 4 1 1 1 1 1 0 0 1 3 1 1 1 1 1 1 1 0 1 1 1 1 1 1 0 1 3 1 1 1 3 2 1 1 3 2
 1 2 2 1 4 1 1 1 3 1 1 0 1 2 0 1 1 3 2 1 1 3 1]
60
TOPICS
530983
(36, 10)
[2 2 0 1 0 0 0 0 0 1 0 0 1 0 0 2 0 2 3 4 1 1 0 0 1 2 0 4 0 2 0 3 2 2 2 0]
36
TOPICS
583255
(12, 10)
[3 1 1 0 1 2 2 0 4 0 0 1]
12
TOPICS
14808631
(79, 10)
[0 0 2 0 4 0 0 1 3 0 3 0 0 4 1 0 1 2 0 2 0 4 0 1 1 0 1 0 1 1 1 2 1 2 1 1 0
 0 3 1 1 1 0 0 2 0 1 3 1 1 4 4 1 2 1 0 2 1 1 1 0 1 0 0 1 1 0 1 1 0 1 1 4 0
 0 1 1 0 0]
79
TOPICS
15679333
(22, 10)
[2 0 1 1 0 1 1 1 1 3 3 2 0 4 0 4 0 4 3 4 0 2]
22
TOPICS
14487262
(9, 10)
[3 3 1 0 2 0 4 2 1]
9
TOPICS
19115873
(23, 10)
[0 4 0 1 1 0 0 2 0 0 1 1 0 3 4 4 1 0 2 2 0 1 3]
23
TOPICS
17676984
(5, 10)
[2 3 4 1 0]
5
TOPICS
9824
(22, 10)
[4 4 2 1 2 1 3 4 1 1 1 3 2 0 2 0 3 0 0 3 0 0]
22
TOPICS
1868513
(6, 10)
[0 0 4 2 3 1]
6
TOPICS
18944060
(25, 10)
[0 2 1 4 0 0 3 0 2 0 0 0 0 2 3 2 0 1 2 3 1 2 1 4 1]
25
TOPICS
5384923
(45, 10)
[2 2 1 0 2 2 2 2

19330844
(20, 10)
[1 0 2 2 4 0 0 0 4 0 1 3 3 3 3 3 3 3 3 1]
20
TOPICS
13110084
(50, 10)
[4 2 0 0 0 2 0 0 0 0 1 0 0 2 1 1 0 0 2 4 0 2 2 1 3 0 2 0 1 1 0 3 0 2 2 2 1
 2 2 0 1 3 1 2 3 1 0 0 0 3]
50
TOPICS
1071235
(208, 10)
[0 1 1 2 0 0 1 2 4 1 0 1 0 0 1 1 2 4 1 2 0 4 1 1 4 2 1 1 4 2 1 0 0 0 0 0 1
 0 4 2 0 2 2 4 4 0 0 2 2 4 2 0 4 2 2 4 4 2 3 2 3 4 0 2 0 0 4 0 0 2 0 0 2 1
 2 2 2 2 1 2 2 0 1 2 4 0 4 1 0 2 1 4 0 4 2 0 2 0 3 2 4 3 0 4 1 0 0 4 0 0 2
 4 0 4 4 3 2 0 2 0 0 2 4 2 2 2 1 0 2 2 0 4 0 1 4 1 0 0 2 1 2 2 0 1 2 1 0 2
 2 1 1 0 0 2 4 4 4 1 4 0 2 4 3 0 0 1 4 2 1 2 0 2 4 0 2 4 2 0 3 0 2 4 0 4 2
 0 2 0 1 2 1 4 0 0 1 1 3 2 0 0 4 2 2 0 4 1 0 4]
208
TOPICS
18659049
(9, 10)
[2 1 0 1 2 0 3 0 4]
9
TOPICS
5371051
(92, 10)
[1 4 2 1 0 3 4 0 0 1 0 0 1 1 2 0 4 1 3 1 4 1 4 1 1 4 0 1 0 0 4 4 2 0 4 4 1
 1 0 4 0 1 1 0 4 0 0 1 4 0 0 0 1 0 1 0 1 0 1 2 4 1 0 0 2 4 0 1 3 1 4 1 0 4
 1 4 0 3 0 4 2 2 1 3 1 0 0 1 0 2 1 1]
92
TOPICS
16413314
(11, 10)
[4 1 1 3 2 4 2 1 0 0 3]
11
TOPICS
15767124
(47, 10)
[1 4 0 1 2 2 1 2

19734101
(7, 10)
[0 0 0 4 2 3 1]
7
TOPICS
14914016
(53, 10)
[3 2 3 1 0 0 2 0 2 0 2 0 3 2 0 0 0 4 1 4 2 3 1 2 4 4 2 4 0 1 1 1 2 1 0 3 2
 2 1 1 0 3 1 1 0 0 1 2 3 2 0 3 4]
53
TOPICS
8014950
(10, 10)
[2 3 2 3 0 3 1 0 1 4]
10
TOPICS
7854872
(18, 10)
[0 4 0 4 2 1 3 3 3 0 1 0 2 3 1 1 0 1]
18
TOPICS
6181758
(178, 10)
[0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 2 1 0 1 2 2 1 0 1 0 2 0 1 0 2 3 3 0 2
 0 0 0 2 0 0 0 0 1 1 1 0 2 1 0 0 0 3 1 0 0 2 0 0 2 1 1 2 0 2 0 0 0 2 0 0 1
 0 1 4 0 2 0 4 1 3 1 1 4 0 4 0 0 1 1 0 0 1 0 2 0 0 3 0 0 2 1 0 1 0 0 0 0 0
 0 1 0 2 3 0 0 2 0 4 2 0 1 2 2 0 0 4 0 0 1 4 0 0 0 1 0 1 0 1 0 0 0 0 0 4 0
 4 0 1 1 0 3 1 3 0 1 0 0 0 2 2 1 3 2 0 2 0 4 1 2 0 2 4 2 2 2]
178
TOPICS
7741566
(33, 10)
[0 1 1 3 2 4 2 2 4 1 1 2 0 4 2 1 1 1 0 1 1 0 1 1 3 0 0 2 2 0 2 0 0]
33
TOPICS
14111670
(19, 10)
[2 0 1 3 4 2 0 3 0 0 0 1 4 3 1 0 0 0 1]
19
TOPICS
14822424
(37, 10)
[3 1 1 4 1 2 4 0 2 0 1 1 2 1 0 0 0 2 0 1 1 0 0 2 0 1 0 2 1 1 0 1 3 1 2 0 1]
37
TOPICS
11588543
(109, 10)
[2 2 4 2 4 1 2 2 0 4 2 2 2 4 1

7475573
(13, 10)
[1 2 1 2 1 0 4 3 0 4 3 0 3]
13
TOPICS
15524846
(80, 10)
[0 3 4 2 2 2 2 2 0 0 1 2 0 2 0 4 2 0 0 1 2 2 1 2 1 2 0 2 0 1 2 2 2 4 0 2 0
 2 2 1 2 2 2 2 2 0 1 0 2 2 2 3 2 2 0 2 1 2 2 1 2 2 1 2 4 2 2 2 2 1 4 1 2 2
 2 3 2 2 3 3]
80
TOPICS
20035860
(10, 10)
[0 1 2 0 3 3 2 0 1 4]
10
TOPICS
15581608
(27, 10)
[2 1 1 4 1 2 0 1 0 0 1 0 4 4 0 4 4 3 0 2 4 2 0 0 3 1 2]
27
TOPICS
14742722
(30, 10)
[2 4 2 1 1 0 4 2 0 1 1 2 4 0 4 1 1 1 2 1 0 3 4 1 1 2 4 3 0 0]
30
TOPICS
3343428
(76, 10)
[3 2 2 1 0 2 0 0 0 4 4 4 3 3 2 2 2 0 0 0 2 4 0 2 1 2 0 2 1 1 4 0 2 0 2 1 1
 1 1 1 2 2 2 0 0 2 2 3 0 2 0 2 3 0 0 3 4 2 0 1 2 1 1 0 1 0 2 2 2 3 0 2 4 0
 2 0]
76
TOPICS
16363651
(6, 10)
[3 4 0 2 1 0]
6
TOPICS
15417450
(10, 10)
[3 0 1 2 0 1 1 3 2 4]
10
TOPICS
6489209
(26, 10)
[2 1 1 2 1 1 1 4 0 0 0 1 0 0 4 2 2 1 2 4 3 4 1 0 3 2]
26
TOPICS
16733496
(21, 10)
[3 1 0 1 1 3 3 1 3 1 0 4 1 4 0 2 2 2 4 1 4]
21
TOPICS
15342033
(21, 10)
[0 1 1 4 3 0 0 0 4 3 2 4 3 1 2 0 1 1 2 1 0]
21
TOPICS
9229058
(6, 10)
[0 3 4 0 1 2]
6

15524898
(94, 10)
[0 2 0 0 0 2 0 0 1 4 0 3 0 0 0 0 0 0 1 0 1 0 3 0 0 2 0 0 2 2 4 0 1 0 0 3 2
 4 2 0 1 0 0 0 0 0 3 0 0 3 0 0 0 0 0 0 0 0 0 2 3 1 1 1 2 3 2 3 2 3 0 0 3 0
 1 0 2 0 4 2 0 2 0 3 3 1 0 0 3 0 0 0 3 3]
94
TOPICS
14950089
(5, 10)
[3 4 1 2 0]
5
TOPICS
2947662
(115, 10)
[1 1 1 1 2 4 2 0 1 4 4 0 4 2 1 4 2 2 2 4 2 4 0 4 2 2 1 0 2 1 3 2 1 4 2 1 3
 2 0 2 2 4 0 1 1 2 0 4 1 0 2 0 1 0 2 4 2 1 0 0 4 0 1 0 0 0 4 0 2 2 0 2 2 2
 0 4 2 1 2 2 2 4 2 2 2 2 2 0 2 4 2 1 2 0 3 1 1 0 4 0 2 4 2 2 2 2 2 2 0 2 2
 3 1 2 1]
115
TOPICS
17943034
(31, 10)
[2 0 0 0 2 1 1 1 3 2 4 4 0 1 1 3 2 1 0 1 0 1 0 2 1 1 4 0 4 4 0]
31
TOPICS
5885130
(11, 10)
[2 4 0 2 1 0 2 1 0 0 3]
11
TOPICS
13829133
(22, 10)
[0 2 0 0 4 1 1 3 2 0 0 2 0 2 0 1 4 0 4 3 0 1]
22
TOPICS
15264864
(45, 10)
[2 0 1 1 0 3 2 0 0 3 1 2 0 4 0 1 3 2 0 0 0 0 0 0 4 0 3 4 0 2 0 2 2 0 2 2 2
 1 2 2 2 3 1 2 2]
45
TOPICS
18105285
(7, 10)
[3 0 0 0 4 1 2]
7
TOPICS
17975255
(29, 10)
[3 3 0 4 3 2 3 2 1 3 0 4 3 3 1 0 1 1 0 0 0 2 2 2 4 0 0 0 1]
29
TOPICS
15059574
(

19102964
(22, 10)
[0 0 1 2 0 2 1 3 3 0 2 0 2 0 3 2 1 1 2 2 2 4]
22
TOPICS
3278624
(9, 10)
[2 0 0 1 3 4 2 1 2]
9
TOPICS
11687122
(19, 10)
[0 2 0 0 4 2 1 0 1 4 0 1 0 3 1 3 3 3 2]
19
TOPICS
12386020
(25, 10)
[1 1 1 1 0 3 3 1 0 4 0 2 4 0 1 2 0 0 2 1 1 2 0 2 0]
25
TOPICS
3783090
(65, 10)
[0 0 1 3 1 3 1 1 1 0 1 3 0 1 3 3 3 0 0 1 1 0 3 3 1 4 1 3 2 0 3 3 1 0 2 0 3
 0 3 1 0 1 1 3 4 0 0 3 0 3 1 4 3 3 0 3 1 3 4 4 3 3 0 0 0]
65
TOPICS
12023024
(10, 10)
[0 0 2 1 4 3 1 2 0 0]
10
TOPICS
18945347
(12, 10)
[0 3 2 1 0 0 1 2 1 3 2 4]
12
TOPICS
8354938
(48, 10)
[1 0 0 4 1 1 1 1 0 1 0 0 1 0 0 2 0 1 3 0 0 0 0 2 4 1 1 2 0 1 0 2 0 1 0 1 0
 1 4 0 1 4 3 0 0 2 1 3]
48
TOPICS
6609546
(123, 10)
[3 3 3 2 1 0 0 3 0 1 3 3 3 0 1 0 3 3 1 1 1 0 1 1 0 0 1 3 4 3 3 1 0 2 1 3 0
 1 3 3 2 0 0 1 0 0 0 0 1 1 0 1 0 0 0 0 0 1 0 1 0 0 1 0 0 0 0 0 0 0 2 0 3 0
 1 1 2 3 3 0 0 1 2 0 1 0 0 0 3 1 0 0 0 4 0 0 1 0 0 0 4 4 0 0 3 3 0 1 0 0 0
 2 4 3 1 1 0 0 1 1 4 3 0]
123
TOPICS
16750384
(22, 10)
[1 1 2 2 3 0 4 4 3 4 3 1 1 0 3 0 0 0 1 0 1 4]

(6, 10)
[3 2 0 4 1 0]
6
TOPICS
15521407
(41, 10)
[3 0 4 4 0 1 1 2 1 4 4 0 3 3 0 0 3 1 3 1 0 2 2 0 2 0 2 3 4 0 3 0 0 2 3 0 3
 0 4 1 2]
41
TOPICS
6765855
(31, 10)
[4 0 3 1 1 4 2 4 4 0 0 4 0 4 0 3 4 1 3 2 0 0 0 2 2 0 4 0 0 1 1]
31
TOPICS
16272709
(21, 10)
[0 0 0 1 4 0 0 4 3 0 1 0 1 2 3 1 0 2 0 2 2]
21
TOPICS
8624898
(165, 10)
[0 0 0 0 3 0 0 1 0 1 1 1 0 0 0 0 1 0 0 4 0 0 0 2 1 2 0 1 3 0 0 0 0 0 0 0 0
 0 2 3 0 0 4 0 0 1 0 0 4 0 4 1 0 0 2 0 0 0 2 0 0 0 1 0 1 2 0 0 0 0 2 0 0 1
 2 2 2 0 0 0 3 2 2 0 2 0 0 0 0 0 4 0 0 0 1 0 4 0 0 0 0 2 0 0 0 0 0 4 0 0 2
 0 2 0 0 0 0 2 0 0 1 0 0 2 0 2 0 0 0 0 0 0 0 0 2 0 0 0 3 0 0 0 1 0 2 0 0 0
 0 0 4 0 0 1 0 1 0 0 2 4 0 0 0 0 4]
165
TOPICS
6134867
(191, 10)
[1 1 1 2 4 1 1 1 0 3 1 1 3 1 4 1 2 1 1 4 2 1 4 4 4 1 4 1 2 3 0 4 4 1 4 4 2
 1 3 2 4 2 3 1 1 1 4 3 1 1 2 1 1 4 1 1 1 1 3 4 1 3 1 4 1 4 3 1 1 2 1 3 1 1
 4 2 2 2 1 4 1 3 4 2 2 1 1 1 1 1 2 1 4 1 1 1 1 1 1 1 1 2 2 4 4 4 3 4 4 4 3
 2 1 2 1 1 4 1 2 2 4 2 2 3 1 0 1 1 0 2 1 4 4 3 2 2 0 0 1 1 1 2 1 3 3 1 2 1
 1 1 0 3 4

TOPICS
14600925
(5, 10)
[4 3 2 1 0]
5
TOPICS
4587068
(18, 10)
[4 1 0 2 3 2 3 0 4 1 1 0 1 0 1 0 4 0]
18
TOPICS
5784404
(20, 10)
[0 0 3 2 3 0 2 1 2 1 0 2 2 4 0 0 1 4 2 2]
20
TOPICS
3198169
(11, 10)
[4 4 2 1 3 1 1 0 3 2 0]
11
TOPICS
11757166
(117, 10)
[3 4 0 4 2 2 3 4 0 4 4 4 2 2 2 2 2 3 0 2 4 2 4 1 2 4 2 2 2 2 4 4 2 2 2 2 2
 2 2 4 2 2 4 0 0 4 4 0 0 0 0 2 4 2 2 3 0 4 0 4 2 0 2 0 0 2 2 0 4 4 2 0 0 0
 0 4 0 2 0 2 0 2 2 4 0 2 0 2 2 4 1 2 0 4 4 2 2 4 4 0 2 0 4 0 2 0 1 1 2 1 0
 3 2 2 1 4 4]
117
TOPICS
508017
(249, 10)
[4 4 1 3 4 1 1 4 1 0 0 1 4 1 1 1 0 0 2 4 1 2 4 1 4 0 4 1 4 4 4 0 4 4 4 4 1
 0 0 1 4 4 1 0 1 1 4 4 0 1 1 0 0 4 4 1 1 4 4 0 0 4 4 1 0 1 0 4 0 1 1 4 4 4
 3 0 4 4 4 1 1 4 4 4 4 4 4 4 0 4 4 0 4 0 0 0 4 0 0 4 1 4 4 1 0 4 1 1 4 4 4
 4 1 4 0 0 4 0 1 0 1 1 4 0 2 4 1 3 2 4 4 1 0 0 3 0 1 1 0 4 1 4 0 4 4 2 0 4
 1 4 2 1 4 1 0 4 4 4 1 4 0 4 4 4 0 0 1 4 3 2 1 3 0 4 4 0 1 1 0 3 4 1 3 1 1
 4 4 0 1 0 1 1 1 4 4 1 1 4 4 4 1 0 4 4 2 0 0 4 0 4 2 4 0 1 0 0 1 1 1 4 4 4
 1 0 4 4 2 1 2 3 0 4 4 4 1 0 0 4 4

7956634
(20, 10)
[0 4 0 1 0 3 2 1 2 2 4 0 1 0 2 3 4 0 2 2]
20
TOPICS
17567087
(58, 10)
[0 0 0 0 0 2 1 0 0 2 0 4 0 0 4 0 0 0 0 4 0 1 1 0 0 3 0 0 4 3 0 1 0 3 0 0 0
 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 1 0 3 0 0 3]
58
TOPICS
14819274
(5, 10)
[4 3 2 1 0]
5
TOPICS
16312885
(50, 10)
[3 2 0 4 1 2 0 0 0 1 2 2 2 1 3 2 0 1 2 1 2 1 4 3 2 2 3 0 0 3 2 0 2 2 1 1 0
 3 2 1 0 0 0 2 2 0 0 2 0 2]
50
TOPICS
1615033
(323, 10)
[0 1 1 0 4 1 0 4 1 2 2 1 0 0 1 1 1 0 0 1 0 0 2 0 0 0 0 0 0 1 0 0 1 2 1 0 1
 1 4 0 1 4 0 1 0 4 0 1 1 0 0 1 4 0 2 0 0 1 0 1 0 1 1 1 4 1 1 1 1 0 4 0 0 4
 1 1 2 4 2 0 1 0 1 2 2 1 0 0 1 1 0 0 1 1 1 1 0 2 1 2 0 1 0 1 1 1 0 0 4 0 1
 2 1 0 0 2 1 0 1 0 1 0 0 1 1 4 0 1 1 0 0 1 0 1 1 0 0 0 1 0 1 1 1 1 4 1 1 2
 1 1 2 2 1 4 1 1 0 1 0 0 0 0 1 1 0 1 0 0 1 1 2 1 1 4 0 0 0 0 0 0 1 4 4 0 1
 3 2 1 4 1 0 4 0 1 0 0 4 0 2 4 1 1 0 0 1 0 1 1 2 1 1 3 1 1 2 0 4 0 0 4 1 1
 0 0 1 0 0 0 0 1 1 4 2 0 0 0 0 0 0 0 1 4 0 0 4 0 0 0 0 0 1 4 0 1 0 1 0 3 2
 0 0 0 0 1 0 4 1 1 1 1 4 0 1 0 0 0 0 4 0 0 1 0 0 0 0 0 1 2 0 0 0 2 0 0 0

1141888
(75, 10)
[2 0 0 0 0 0 0 0 0 2 0 0 0 0 3 0 0 0 4 1 0 4 0 2 2 3 0 0 0 1 4 1 2 0 0 0 1
 1 0 0 0 0 0 0 0 0 2 0 1 2 1 0 1 2 0 4 0 0 0 0 0 2 0 2 0 0 0 0 2 0 0 4 2 0
 0]
75
TOPICS
5870922
(91, 10)
[2 0 3 0 1 2 1 2 1 1 0 1 2 0 2 0 1 0 4 2 2 2 1 4 1 2 3 2 0 3 3 2 3 2 0 2 3
 2 2 0 1 0 1 2 0 2 2 1 0 1 2 1 2 2 0 0 0 0 2 0 0 0 2 4 0 2 2 1 2 1 4 3 2 2
 0 0 0 3 3 1 1 2 2 2 0 2 3 0 0 2 1]
91
TOPICS
8055839
(5, 10)
[2 4 3 1 0]
5
TOPICS
5899031
(43, 10)
[0 1 0 0 0 3 0 0 2 3 0 2 2 0 3 0 3 1 0 0 0 4 2 2 1 3 1 4 3 2 1 1 0 2 0 1 0
 1 3 0 0 2 0]
43
TOPICS
14071446
(8, 10)
[2 3 4 0 1 1 0 0]
8
TOPICS
12221012
(7, 10)
[1 1 0 3 4 0 2]
7
TOPICS
17075037
(24, 10)
[1 2 1 1 0 0 4 2 2 1 4 1 2 1 0 3 2 2 0 0 1 3 0 0]
24
TOPICS
11686744
(21, 10)
[1 3 3 2 2 0 1 4 3 1 1 1 0 0 0 0 1 1 2 0 4]
21
TOPICS
5581575
(66, 10)
[4 4 0 2 4 1 1 0 1 2 4 4 4 1 0 1 2 1 1 1 3 2 0 0 2 0 1 1 1 0 1 1 4 0 4 0 1
 4 1 4 1 0 0 0 0 2 0 4 0 3 4 2 4 4 0 0 0 0 2 0 0 0 0 4 1 4]
66
TOPICS
3457722
(30, 10)
[2 4 1 2 4 1 3 4 1 2 3 3 4 4 1 0 1 0 1

TOPICS
7740436
(27, 10)
[3 3 3 0 1 0 2 3 1 2 4 0 3 0 0 1 1 1 4 1 1 1 0 0 1 0 1]
27
TOPICS
11688611
(14, 10)
[0 4 2 1 0 0 3 3 3 2 0 1 4 2]
14
TOPICS
14786796
(15, 10)
[1 4 4 4 0 3 0 3 2 4 1 2 0 1 0]
15
TOPICS
2135075
(127, 10)
[1 1 1 1 3 4 1 1 1 1 1 1 4 1 0 1 1 0 4 4 1 1 0 0 1 4 1 1 1 4 1 1 0 1 1 3 1
 4 1 1 1 0 1 3 1 1 1 1 4 1 1 4 1 4 1 1 0 2 3 0 0 4 1 0 1 0 1 4 1 0 1 0 0 1
 1 1 1 0 1 1 1 1 4 1 1 4 4 1 1 1 1 1 1 1 4 1 1 1 1 4 1 1 0 1 1 1 1 4 4 4 1
 1 1 4 1 0 4 0 4 4 1 2 4 2 4 0 1]
127
TOPICS
14789788
(19, 10)
[2 2 0 0 0 3 0 0 0 4 0 0 4 1 4 1 2 2 3]
19
TOPICS
13433298
(83, 10)
[0 4 0 0 0 1 0 0 0 0 4 0 0 4 0 0 0 0 0 4 0 1 0 0 1 1 1 4 0 0 0 0 0 0 1 0 1
 1 0 4 0 4 1 0 2 1 0 2 4 1 4 4 0 1 0 1 4 0 1 1 4 1 1 4 0 0 1 1 1 4 1 0 1 0
 0 1 1 3 1 1 3 4 1]
83
TOPICS
12290886
(8, 10)
[2 0 2 3 4 0 1 1]
8
TOPICS
3434614
(39, 10)
[2 2 0 2 1 3 0 1 2 0 0 1 4 1 1 3 4 0 2 1 0 1 1 4 2 4 0 2 4 3 1 0 1 4 4 4 2
 0 3]
39
TOPICS
9425902
(14, 10)
[1 0 2 1 0 3 1 0 2 4 4 3 0 0]
14
TOPICS
3164650
(16, 10)
[1 0 1 4 1 0

24
TOPICS
4875342
(11, 10)
[1 1 1 2 0 4 2 0 3 2 3]
11
TOPICS
12665563
(27, 10)
[2 1 1 3 0 4 1 3 1 3 4 1 1 3 0 1 0 2 0 0 2 0 0 3 1 2 4]
27
TOPICS
19138622
(8, 10)
[1 1 1 4 0 2 0 3]
8
TOPICS
13918656
(5, 10)
[2 4 3 1 0]
5
TOPICS
801680
(29, 10)
[4 4 2 3 4 2 4 2 0 1 2 0 1 0 3 0 2 2 4 2 0 1 1 1 2 0 1 0 0]
29
TOPICS
3914729
(5, 10)
[4 2 3 1 0]
5
TOPICS
20135997
(7, 10)
[0 4 3 1 0 2 0]
7
TOPICS
16514756
(50, 10)
[0 0 0 0 0 0 0 3 0 0 0 3 0 1 0 0 0 3 2 2 0 0 0 3 1 2 0 0 0 0 1 0 0 4 0 2 0
 2 1 0 4 0 0 0 2 1 4 3 4 4]
50
TOPICS
18617002
(6, 10)
[3 4 1 2 0 0]
6
TOPICS
6378076
(45, 10)
[2 2 2 2 1 2 1 2 2 0 4 1 2 0 4 2 2 2 2 0 1 2 0 2 2 1 1 2 4 3 4 4 0 0 4 0 3
 2 4 1 3 0 1 4 4]
45
TOPICS
20038847
(7, 10)
[3 2 2 4 0 0 1]
7
TOPICS
16941879
(25, 10)
[1 1 0 0 4 0 0 4 3 0 0 0 4 0 2 2 1 1 0 1 1 0 1 3 1]
25
TOPICS
4964365
(11, 10)
[4 0 1 3 0 4 2 2 0 2 1]
11
TOPICS
20255529
(14, 10)
[2 3 0 1 4 0 0 2 4 1 3 0 0 1]
14
TOPICS
9727523
(79, 10)
[0 0 0 0 0 1 1 0 4 1 3 0 0 0 0 0 3 0 0 0 0 0 0 0 0 0 3 0 0 0 0 0 0 0 

44
TOPICS
3432321
(82, 10)
[0 0 0 1 0 4 0 0 2 0 0 2 0 2 0 0 2 2 4 1 2 0 4 4 4 1 4 4 2 0 3 4 0 1 4 1 0
 1 0 4 0 4 2 0 4 0 3 4 0 1 1 0 4 0 0 4 2 0 1 0 0 0 0 0 1 1 1 0 0 1 0 0 2 0
 2 4 0 1 4 0 1 0]
82
TOPICS
17523630
(36, 10)
[0 2 0 0 2 0 1 0 0 0 4 1 0 2 0 3 4 1 2 0 1 0 0 1 1 0 4 0 3 0 2 2 0 4 0 3]
36
TOPICS
16447567
(28, 10)
[4 3 1 3 0 1 0 4 0 3 1 4 1 1 2 1 1 1 3 1 1 4 1 1 2 2 2 0]
28
TOPICS
1587540
(32, 10)
[1 1 1 3 3 1 3 0 3 4 3 1 4 1 0 4 2 2 4 1 0 2 3 1 0 1 3 0 1 0 1 4]
32
TOPICS
7961477
(15, 10)
[0 0 4 3 1 2 1 0 2 3 4 1 3 0 0]
15
TOPICS
16364879
(42, 10)
[0 0 0 4 0 0 2 0 0 0 4 0 0 0 0 0 0 0 3 2 0 0 0 2 3 0 2 0 1 0 2 1 1 0 0 4 1
 2 0 0 3 0]
42
TOPICS
14461998
(14, 10)
[4 0 0 2 0 1 0 2 3 1 1 2 3 4]
14
TOPICS
18124698
(22, 10)
[3 0 1 1 3 4 2 4 2 1 3 3 1 0 1 1 1 0 0 0 0 0]
22
TOPICS
10293480
(5, 10)
[4 3 1 2 0]
5
TOPICS
13820571
(62, 10)
[4 0 1 1 0 0 1 0 0 1 1 1 1 1 4 0 1 3 1 0 1 0 0 4 0 1 0 0 0 4 3 2 2 0 1 3 1
 4 1 0 4 1 1 0 0 0 0 1 0 0 1 0 1 0 1 1 1 0 1 1 1 3]
62
TOPICS
17656957
(12, 1

12318093
(11, 10)
[2 1 1 4 3 0 2 1 4 0 3]
11
TOPICS
18944289
(27, 10)
[3 2 4 1 1 0 0 1 0 1 0 1 2 0 3 1 3 0 2 2 4 0 3 4 4 1 0]
27
TOPICS
16274814
(14, 10)
[2 1 1 3 1 0 4 0 0 1 0 4 2 1]
14
TOPICS
17386330
(33, 10)
[1 1 0 2 0 1 4 2 2 1 1 1 1 1 1 2 3 2 1 1 1 4 2 3 0 2 0 0 1 1 2 1 0]
33
TOPICS
9231486
(72, 10)
[1 1 1 1 1 0 0 0 0 1 0 1 0 4 1 4 0 1 1 1 2 1 1 0 1 0 1 0 0 0 0 0 0 1 2 3 1
 3 1 1 1 2 1 0 1 0 0 0 0 1 2 2 0 0 0 0 1 0 2 0 0 2 0 1 2 4 1 0 1 0 0 0]
72
TOPICS
11784924
(12, 10)
[0 0 0 0 4 2 2 1 3 1 0 2]
12
TOPICS
4995033
(53, 10)
[1 0 0 1 4 0 0 0 3 0 1 0 0 0 0 0 1 1 0 0 4 0 1 1 0 0 3 2 0 0 0 0 1 0 0 1 2
 0 4 1 1 1 0 0 1 2 3 4 2 0 1 0 0]
53
TOPICS
1074406
(54, 10)
[0 1 1 3 0 4 3 2 0 1 4 0 1 0 1 0 1 0 0 3 3 0 4 0 0 3 1 0 3 2 0 2 1 4 2 2 0
 0 3 0 0 0 4 4 1 0 0 4 0 1 0 0 1 1]
54
TOPICS
18345436
(12, 10)
[0 1 0 2 2 3 2 3 2 4 1 0]
12
TOPICS
17169007
(28, 10)
[3 2 2 0 1 0 0 0 3 0 1 1 1 1 0 4 1 3 0 0 0 1 4 3 0 0 0 0]
28
TOPICS
10032327
(26, 10)
[1 4 0 3 4 4 0 1 0 0 4 2 0 2 0 3 2 0 2 3 2 1 2 1 3

10494550
(146, 10)
[1 1 1 1 1 1 1 1 0 0 1 4 1 1 1 1 1 1 1 2 1 3 1 1 4 1 0 1 0 1 1 1 1 1 1 1 1
 1 1 0 1 4 2 1 1 1 4 1 1 1 1 1 0 1 1 1 0 1 1 1 3 1 1 4 1 1 1 3 1 1 1 1 1 1
 1 1 4 1 0 1 4 1 1 1 2 0 1 0 0 0 1 1 1 1 0 1 1 1 3 4 4 1 1 1 0 1 1 1 2 1 2
 2 1 1 1 0 1 1 0 1 0 1 3 1 1 0 1 2 0 1 1 1 0 1 3 2 1 1 1 1 1 2 1 1 1 3]
146
TOPICS
19670771
(35, 10)
[0 0 2 0 0 1 0 2 0 2 1 2 2 2 2 1 2 0 2 2 3 0 2 4 1 2 3 2 3 0 3 1 0 4 2]
35
TOPICS
13126713
(9, 10)
[0 4 4 0 1 3 1 0 2]
9
TOPICS
39116
(68, 10)
[0 4 0 2 0 2 0 0 0 1 0 0 0 0 4 0 0 4 0 0 0 1 4 4 0 2 1 0 3 4 4 0 0 4 0 1 1
 0 0 0 0 0 0 1 2 0 2 0 4 1 2 0 2 3 2 1 1 0 0 1 3 4 0 0 1 0 0 0]
68
TOPICS
13531200
(34, 10)
[0 2 4 1 1 0 0 1 4 4 4 1 0 1 0 0 3 0 4 0 4 4 4 1 2 0 3 1 1 1 0 3 2 0]
34
TOPICS
5739119
(40, 10)
[3 4 0 2 2 0 3 0 0 0 1 3 1 0 3 2 2 2 2 2 0 2 1 3 3 1 2 0 2 1 1 0 2 3 4 0 2
 0 0 2]
40
TOPICS
8480507
(22, 10)
[0 0 3 4 0 0 2 2 4 4 2 2 4 4 3 1 1 1 2 2 0 1]
22
TOPICS
15989113
(40, 10)
[3 1 0 4 1 1 1 1 1 0 2 4 0 2 1 0 0 4 0 0 4 1 2 2 0 2 0 2 1 2 1 1

13378923
(55, 10)
[0 0 4 4 4 0 2 0 0 4 0 3 0 3 0 1 3 0 0 2 2 2 1 0 2 2 1 0 2 1 0 0 1 0 3 2 3
 4 4 1 4 1 3 1 1 0 0 0 3 0 2 4 4 3 0]
55
TOPICS
1864705
(11, 10)
[3 2 3 2 0 1 1 0 2 1 4]
11
TOPICS
18459463
(27, 10)
[3 0 3 1 0 3 0 1 3 4 1 2 2 0 0 1 4 0 3 1 0 4 0 1 1 1 4]
27
TOPICS
6602167
(90, 10)
[2 3 3 2 2 2 1 2 4 0 1 2 3 2 3 4 2 1 2 0 0 2 1 2 2 2 1 3 4 3 0 2 2 0 2 0 3
 2 2 4 3 1 2 2 2 1 2 2 1 4 1 2 3 2 1 0 3 2 2 2 2 2 2 2 2 2 2 3 1 1 2 0 2 1
 1 3 3 0 2 0 0 1 0 2 1 2 2 2 4 2]
90
TOPICS
10656899
(6, 10)
[3 4 0 2 1 0]
6
TOPICS
886668
(26, 10)
[2 0 1 1 2 0 0 4 1 2 1 3 2 4 0 0 0 0 1 0 2 4 2 0 4 3]
26
TOPICS
1510876
(26, 10)
[4 4 1 2 1 1 0 0 0 2 1 0 3 1 4 1 4 3 4 4 3 0 2 2 1 0]
26
TOPICS
8025718
(23, 10)
[0 2 0 4 0 1 3 1 0 1 4 0 1 2 4 3 0 1 1 0 3 3 1]
23
TOPICS
18508677
(51, 10)
[0 1 2 3 2 1 0 4 3 0 0 0 4 3 1 3 0 2 4 3 2 0 0 0 3 4 1 4 1 3 3 3 0 4 2 3 2
 1 1 0 0 0 4 3 1 3 0 2 2 4 0]
51
TOPICS
18690685
(20, 10)
[1 0 1 2 4 1 4 0 2 0 4 0 0 0 1 2 3 3 0 4]
20
TOPICS
15255593
(39, 10)
[1 0 0 0 1 3 0 1

5269216
(66, 10)
[0 1 0 0 1 0 0 1 1 1 0 1 1 4 2 1 1 0 0 0 1 1 2 0 0 0 1 1 1 1 0 3 0 1 1 0 3
 1 1 1 4 4 1 4 4 0 1 1 1 0 4 1 3 4 0 0 4 0 1 1 1 0 1 0 1 1]
66
TOPICS
1115394
(215, 10)
[0 0 1 0 0 4 4 1 0 2 1 1 0 4 1 1 0 0 0 0 1 1 0 0 2 0 0 4 0 1 1 4 1 1 0 1 0
 2 4 1 0 1 4 0 1 3 2 0 0 0 3 1 0 0 0 0 2 4 0 0 1 1 0 4 0 4 1 0 0 0 4 4 1 0
 0 4 0 0 0 0 1 4 0 1 0 1 0 0 0 0 0 0 1 0 0 4 3 2 0 0 0 1 0 2 4 4 3 0 2 0 1
 0 0 2 2 0 0 4 3 4 0 0 0 0 0 1 0 0 3 0 1 1 0 1 4 4 0 0 0 0 1 2 0 4 0 0 4 4
 4 0 0 4 4 1 1 0 0 0 1 4 1 1 3 4 4 0 1 1 4 4 4 1 4 2 3 2 4 4 0 4 1 1 1 1 0
 1 0 2 1 1 4 0 4 4 4 4 1 3 4 4 3 1 4 4 0 3 4 4 0 1 4 0 0 1 1]
215
TOPICS
15173372
(25, 10)
[2 1 1 1 3 3 0 4 3 3 1 3 0 0 4 0 0 1 2 4 1 1 2 1 0]
25
TOPICS
6870485
(7, 10)
[0 4 2 3 0 1 1]
7
TOPICS
17920249
(5, 10)
[2 3 4 1 0]
5
TOPICS
18448985
(35, 10)
[4 1 0 1 2 4 1 0 0 3 1 1 1 2 4 0 3 3 1 3 0 1 4 3 2 4 4 2 4 2 2 4 0 0 3]
35
TOPICS
5726250
(24, 10)
[4 3 0 0 3 0 0 1 1 0 4 1 1 1 2 0 2 1 1 2 4 0 2 2]
24
TOPICS
8231382
(80, 10)
[4 0 1 1 3 1 3 1 4 

TOPICS
3755609
(35, 10)
[4 4 1 1 1 1 3 0 1 0 1 0 2 2 1 0 2 0 0 0 0 1 0 3 0 3 2 1 2 3 1 3 2 2 1]
35
TOPICS
18485290
(29, 10)
[2 1 0 2 0 4 0 0 1 1 4 3 3 4 3 0 0 1 4 4 0 0 3 0 1 2 1 1 0]
29
TOPICS
15148487
(41, 10)
[3 1 1 2 1 1 1 4 1 0 0 1 2 2 1 0 4 1 0 3 2 0 0 0 4 0 1 0 1 0 2 4 2 0 0 0 2
 1 0 2 2]
41
TOPICS
19199046
(45, 10)
[0 1 0 0 0 1 4 3 0 3 1 1 3 0 0 1 0 0 3 3 1 4 1 2 3 3 1 1 3 1 3 2 0 3 1 1 1
 1 0 3 1 1 0 1 0]
45
TOPICS
5592866
(16, 10)
[1 3 1 3 4 2 1 1 2 4 3 1 2 3 0 0]
16
TOPICS
197727
(30, 10)
[1 3 4 3 0 1 3 0 4 4 0 2 4 4 2 1 2 1 0 4 0 1 4 0 2 2 1 2 4 0]
30
TOPICS
2372459
(9, 10)
[3 0 0 1 0 1 2 4 3]
9
TOPICS
14575184
(36, 10)
[1 0 1 3 0 0 1 0 0 4 1 0 3 0 0 1 1 0 2 2 0 0 3 4 2 1 0 0 1 0 2 2 0 0 1 4]
36
TOPICS
10070404
(35, 10)
[4 4 0 0 1 1 0 3 0 3 3 1 1 0 2 0 0 2 0 0 3 0 1 1 0 0 0 3 1 2 1 0 0 0 0]
35
TOPICS
9072821
(5, 10)
[3 4 2 1 0]
5
TOPICS
18193553
(7, 10)
[0 2 1 4 0 3 1]
7
TOPICS
13652639
(10, 10)
[4 1 2 3 2 1 0 3 4 0]
10
TOPICS
17296595
(10, 10)
[0 1 1 0 1 2 4 0 3 2]
10
TOPI

TOPICS
2216767
(70, 10)
[4 4 0 2 0 2 1 0 2 1 1 2 0 2 2 1 2 2 1 3 1 0 0 4 4 1 4 2 1 2 4 1 4 0 1 3 0
 2 4 2 1 4 4 2 4 4 2 2 2 4 0 0 4 4 3 1 1 4 2 2 2 0 1 1 0 0 3 0 1 4]
70
TOPICS
1009275
(27, 10)
[4 2 4 2 3 0 2 1 4 3 1 2 1 2 2 1 4 1 0 0 2 1 2 1 2 1 0]
27
TOPICS
19545605
(5, 10)
[3 4 1 2 0]
5
TOPICS
13586128
(10, 10)
[0 1 2 4 0 3 1 3 0 2]
10
TOPICS
8309711
(86, 10)
[0 1 1 0 0 0 0 0 3 1 3 4 2 0 0 0 0 0 1 1 1 2 1 0 4 1 1 2 1 1 0 1 4 0 1 1 1
 0 1 0 0 1 1 0 1 0 0 4 0 1 3 0 1 0 0 0 1 1 1 1 0 4 1 0 1 1 0 4 1 0 0 4 0 1
 0 1 1 4 1 0 1 4 0 1 1 0]
86
TOPICS
16459191
(42, 10)
[1 1 1 1 4 3 3 3 1 1 2 3 1 0 3 3 4 0 0 2 1 3 3 1 1 4 1 2 0 3 4 3 1 1 1 0 0
 1 0 0 4 3]
42
TOPICS
6065674
(18, 10)
[2 0 0 1 0 3 0 3 4 1 2 4 0 1 0 0 1 2]
18
TOPICS
20392363
(10, 10)
[1 0 3 1 2 4 3 4 2 0]
10
TOPICS
9676551
(174, 10)
[0 0 0 0 0 0 0 4 2 0 1 0 0 0 0 0 1 0 0 0 0 0 0 4 0 0 0 0 0 0 2 1 0 0 0 3 0
 1 0 0 0 0 0 0 0 0 0 2 2 0 0 0 0 0 0 0 3 0 2 2 3 0 0 0 0 0 0 0 1 1 0 0 2 0
 0 0 0 2 0 0 0 0 0 0 0 2 0 4 0 0 0 0 0 0 0 0 0 0 0 

7474855
(15, 10)
[3 4 0 2 0 0 1 2 1 0 1 1 3 4 2]
15
TOPICS
14083611
(156, 10)
[4 0 0 0 0 2 2 4 4 3 1 3 1 1 2 0 1 2 4 1 3 1 1 2 1 0 0 1 4 4 4 0 0 3 2 0 3
 4 2 1 1 0 2 2 4 0 4 2 0 4 2 4 0 1 0 1 4 2 0 2 2 2 4 2 0 2 1 4 3 0 0 1 0 2
 4 4 0 4 1 0 3 0 0 3 4 4 2 2 0 3 4 2 2 4 0 1 1 4 3 4 4 1 0 1 4 3 1 2 4 0 3
 1 0 2 3 4 4 2 2 2 1 0 2 4 4 2 3 2 3 0 4 3 4 2 0 0 1 0 0 4 3 1 1 2 1 4 1 1
 2 2 2 0 0 0 0 1]
156
TOPICS
12962923
(7, 10)
[0 4 2 2 0 3 1]
7
TOPICS
17710012
(26, 10)
[2 4 2 0 0 3 4 0 3 1 3 0 3 1 0 2 4 2 2 2 0 4 2 1 3 2]
26
TOPICS
16904896
(5, 10)
[2 4 3 1 0]
5
TOPICS
2701124
(51, 10)
[0 2 1 0 0 0 3 4 2 4 0 0 0 1 1 0 2 0 0 0 2 0 2 3 3 4 0 0 2 2 2 4 2 4 2 1 0
 0 1 3 4 2 4 0 1 1 0 1 3 1 2]
51
TOPICS
12143408
(35, 10)
[0 0 0 4 0 1 1 0 3 3 0 4 3 1 0 1 1 1 0 2 2 1 1 0 0 0 0 2 1 0 0 0 3 0 0]
35
TOPICS
18377950
(5, 10)
[3 2 4 1 0]
5
TOPICS
11589644
(29, 10)
[2 1 1 2 2 1 2 3 2 1 0 0 3 1 2 1 0 1 1 0 0 2 0 2 2 0 0 4 4]
29
TOPICS
4687499
(24, 10)
[2 3 1 2 0 0 1 0 0 2 2 1 4 0 0 3 1 0 2 0 1 0 4 0]
24
TOP

14566386
(38, 10)
[1 0 0 0 0 1 4 1 0 0 1 0 0 0 0 0 0 2 1 0 1 2 0 0 2 3 0 3 0 2 0 1 4 0 0 4 3
 0]
38
TOPICS
16540349
(34, 10)
[0 0 3 1 4 2 0 0 1 0 2 2 4 2 2 2 2 2 2 2 1 0 3 0 2 2 1 3 1 1 2 0 1 2]
34
TOPICS
20711007
(6, 10)
[2 0 3 4 1 0]
6
TOPICS
18823105
(12, 10)
[1 2 4 4 3 3 2 1 2 0 0 0]
12
TOPICS
19384244
(6, 10)
[0 2 4 3 1 0]
6
TOPICS
18575841
(28, 10)
[3 0 4 1 2 3 3 1 1 1 1 1 2 1 0 0 0 1 4 0 0 1 3 4 0 1 3 2]
28
TOPICS
10004575
(14, 10)
[3 3 3 0 1 1 0 4 2 2 2 1 0 0]
14
TOPICS
14994629
(78, 10)
[0 3 1 3 1 3 3 1 3 0 0 0 3 3 1 3 3 1 3 3 0 1 3 0 3 3 2 3 1 0 1 1 1 3 1 3 1
 1 3 0 3 3 1 1 1 3 1 1 3 3 4 1 3 1 3 3 3 3 3 1 3 1 3 1 3 4 1 2 3 1 0 0 1 1
 1 1 3 3]
78
TOPICS
11710680
(14, 10)
[4 3 1 0 2 2 1 0 2 4 0 4 1 0]
14
TOPICS
4699828
(58, 10)
[0 0 2 0 0 0 0 4 0 4 0 0 0 0 3 0 0 1 2 1 1 1 1 1 1 1 1 1 4 0 0 0 0 0 2 2 0
 2 2 0 0 2 0 0 0 2 0 0 0 0 0 0 0 0 2 0 0 3]
58
TOPICS
1340290
(9, 10)
[0 2 1 2 0 3 1 4 2]
9
TOPICS
8780440
(17, 10)
[2 1 1 2 2 3 3 4 0 0 0 0 0 0 1 4 3]
17
TOPICS
8227206
(26, 10)


In [31]:
results_df.to_csv("Result_HAC.csv",columns=["Topics_HAC","Review_comments","Review_Id","Listing_Id","Documents","Cluster_HAC"])